name: Deploy to Firebase Hosting on merge
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
      - run: npm ci || true
      - run: npm run build || true
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          channelId: live
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_PROJECT_634284468189198620 }}
          projectId: project-634284468189198620
